import Head from 'next/head'
import Image from 'next/image'
import Blog from '../components/Blog'

export default function Home() {
  return (
    <div className="bg-slate-200 h-screen">
      <Head>
        <title>Trizza blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Blog/>

      
    </div>
  )
}
