import Head from 'next/head'
import Image from 'next/image'

import   {  gql, GraphQLClient } from 'graphql-request'
import Blogs from '../components/Blogs';


const graphcms = new GraphQLClient(
  "https://api-us-east-1.hygraph.com/v2/clbovm8rw0pel01t6bac9do5n/master"
);
const Query = gql`
query  {
  posts {
    createdAt
    
    datePublishes
    id
    little
    content{
      html
    }
    publishedAt
    slug
    title
    updatedAt
    coverPhoto{
      url
    }
    author {
      name
      avatar{
        url
      }
    }
  }
}

`
export async function getStaticProps() {
  const results = await graphcms.request(Query); 
  return {
    props: {
      results,
    },
    revalidate: 20,
  }

}

export default function Home({ results }) {
  
  return (
    <div className="  ">
      <Head>
        <title>Trizza blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-4xl mx-auto p-4  ">
        {results.posts.map((post) => (
        <Blogs
          key={post.id}
          post = {post.post}
          authorAvatar= {post.author.avatar.url}
          id = {post.id}
          authorName = {post.author.name}
          photo = {post.coverPhoto.url}
          date = {post.datePublishes}
          short = {post.little}
          slug = {post.slug}
          title = {post.title}
        />
        ))}
      </div>
      

      

      
    </div>
  )
}
